# because ui isn't the core of the project
# the following code is completely generated by AI and only slightly changed
import streamlit as st
import requests

API_BASE = "http://127.0.0.1:8000/api"

st.set_page_config(page_title="Edge Vocab Tutor", layout="wide")
st.title("📚 Edge-Native GRE Vocab Tutor")

# ==========================================
# Session State
# ==========================================
if "current_card" not in st.session_state:
    st.session_state.current_card = None

# ==========================================
# 區塊 1：生成單字與相似度聚合
# ==========================================
st.header("1. Vocabulary Generation & Clustering")
word_input = st.text_input("Enter a GRE word:", key="word_input")

if st.button("Generate Card & Find Similar"):
    if word_input:
        with st.spinner("Generating vocabulary card via Local LLM..."):
            try:
                gen_res = requests.post(f"{API_BASE}/generate", json={"word": word_input})

                if gen_res.status_code == 200:
                    st.session_state.current_card = gen_res.json()
                    st.success("Generation Complete!")
                else:
                    st.error(f"Error: {gen_res.text}")

            except requests.exceptions.ConnectionError:
                st.error("Cannot connect to Backend API. Is FastAPI running?")

# 只要 Session State 裡有單字卡，就渲染畫面
if st.session_state.current_card:
    card = st.session_state.current_card

    col1, col2 = st.columns(2)

    with col1:
        st.subheader(card["word"].capitalize())
        st.caption(f"CEFR Level: {card['cefr_level']}")
        for idx, sense in enumerate(card["senses"]):
            st.markdown(f"**{idx+1}. {sense['part_of_speech']}**")
            st.write(sense["definition"])

        st.markdown("**Synonyms:** " + ", ".join(card.get("synonyms", [])))
        st.markdown("**Antonyms:** " + ", ".join(card.get("antonyms", [])))

    with col2:
        st.subheader("Semantic Cluster")
        st.write("Words closest in Vector Space:")
        try:
            sim_res = requests.get(f"{API_BASE}/similar/{card['word']}?top_k=5")
            if sim_res.status_code == 200:
                sim_data = sim_res.json()
                for item in sim_data:
                    # 避免 Similarity 出現負數或超過 1 導致 progress bar 報錯
                    progress_val = max(0.0, min(1.0, float(item["similarity"])))
                    st.progress(progress_val, text=f"{item['word']} ({item['similarity']:.2f})")
            else:
                st.warning("Not enough words in database to form a cluster.")
        except:
            st.error("Vector search failed.")

    # ==========================================
    # 區塊 2：動態造句與 CoT 批改
    # ==========================================
    st.divider()
    st.header("2. CoT Sentence Evaluation")
    st.write(f"Test your understanding by writing a sentence using the word **{card['word']}**.")

    user_sentence = st.text_area("Your Sentence:", placeholder="Type your sentence here...")

    if st.button("Evaluate Sentence"):
        if user_sentence:
            with st.spinner("Evaluating via CoT reasoning..."):
                # 取出第一個定義作為評判標準
                target_def = card["senses"][0]["definition"] if card.get("senses") else ""

                payload = {
                    "word": card["word"],
                    "definition": target_def,
                    "user_sentence": user_sentence
                }

                try:
                    eval_res = requests.post(f"{API_BASE}/evaluate", json=payload)

                    if eval_res.status_code == 200:
                        evaluation = eval_res.json()

                        # 根據 is_appropriate 改變 UI 顏色
                        if evaluation["is_appropriate"]:
                            st.success("✅ Appropriate Usage!")
                        else:
                            st.error("❌ Incorrect or Unnatural Usage")

                        # 顯示模型背後的思考過程與最終回饋
                        st.markdown("### AI Reasoning (Chain-of-Thought)")
                        st.write(evaluation["reasoning"])

                        st.markdown("### Feedback & Suggestions")
                        st.info(evaluation["feedback"])
                    else:
                        st.error(f"Error: {eval_res.text}")
                except Exception as e:
                    st.error(f"Evaluation request failed: {e}")
        else:
            st.warning("Please enter a sentence before evaluating.")